spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://host.docker.internal:5432/faang}
    username: ${DATABASE_USERNAME:user}
    password: ${DATABASE_PASSWORD}
    hikari:
      auto-commit: false
      schema: ${DATABASE_SCHEMA:post_service}
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: ${SHOW_SQL:true}
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DATABASE_SCHEMA:post_service}

  servlet:
    multipart:
      max-file-size: 10MB

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    default-schema: ${DATABASE_SCHEMA:post_service}
    liquibase-schema: ${DATABASE_SCHEMA:post_service}

  kafka:
    bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
    topics:
      analytics-comment-topic:
        name: ${KAFKA_ANALYTICS_COMMENT_TOPIC:analytics_comment_topic}
      notification-like-topic:
        name: ${KAFKA_NOTIFICATION_LIKE_TOPIC:notification_like_topic}
      notification-comment-topic:
        name: ${KAFKA_NOTIFICATION_COMMENT_TOPIC:notification_comment_topic}
      user-ban-topic:
        name: ${KAFKA_USER_BAN_TOPIC:user_ban_topic}
      publish-post-topic:
        name: ${KAFKA_PUBLISH_POST_TOPIC:publish_post_topic}
        subscribers-batch-size: 1000
      publish-post-view-topic:
        name: ${KAFKA_PUBLIC_POST_VIEW_TOPIC:public_post_view_topic}

  data:
    redis:
      host: ${REDIS_URL:host.docker.internal}
      port: ${REDIS_PORT:6379}
      ttl-days: 1
      channels:
        calculations_channel:
          name: ${REDIS_CALCULATIONS_CHANEL:calculations_channel}

springdoc:
  swagger-ui:
    path: "/documentation.html"
    enabled: ${SWAGGERUI_ENABLED:true}
  api-docs:
    enabled: ${API_DOCS_ENABLED:true}
  title: "Post service API"
  version: "0.1.0.1"
  description: "Post service gives the ability to write text posts to share your thoughts, knowledge and information with other users."

server:
  port: ${POST_SERVICE_PORT:8081}

logging:
  level:
    root: info
    liquibase: info

aws:
  s3:
    endpoint: ${MINIO_SERVICE_HOST:http://localhost:9000}
    accessKey: ${MINIO_ACCESS_KEY}
    secretKey: ${MINIO_SECRET_KEY}
    bucket: ${MINIO_BUCKET_NAME:corpbucket}
    region: us-east-1
    maxConcurrency: 50
    connectionTimeout: 60s
    readTimeout: 60s
    writeTimeout: 60s
    apiCallTimeout: 2m
    apiCallAttemptTimeout: 90s    

comment:
  image:
    largeImageMaxSize: 1080
    smallImageMaxSize: 170
    max-file-size: 5MB

project-protocol: http

project-service:
  host: ${PROJECT_SERVICE_HOST:localhost}
  port: ${PROJECT_SERVICE_PORT:8082}
  endpoints:
    getById: /api/v1/projects/{id}
user-service:
  host: ${USER_SERVICE_HOST:localhost}
  port: ${USER_SERVICE_PORT:8080}  
  endpoints:
    getById: /api/v1/users/{id}
payment-service:
  host: ${PAYMENT_SERVICE_HOST:localhost}
  port: ${PAYMENT_SERVICE_PORT:8082}

moderation:
  cron: "0 0 0 * * ?"
  threadSize: 100
  api-url: ${MODERATION_API_URL:"https://commentanalyzer.googleapis.com/v1alpha1/comments:analyze?key=AIzaSyCvYJUwADYD2pGzdhoY5QunJEgrvgPbbpg"}
  bad-words-path: ${MODERATION_BAD_WORDS:classpath:moderation/bad-words.json}
  chunk-size: 500
  banned-words-path: ${MODERATION_BANNED_WORDS:classpath:moderation/banned-words.json}

rest-template:
  config:
    connectTimeout: 5000
    readTimeout: 5000

file-controller:
  upload:
    max-files-per-post: 10
    max-files-size-in-post-mb: 5
  image:
    max-width: 1080
    max-height-rectangle: 566

user-banner:
  cron: "0 0 0 * * *"
  posts-count-for-ban: 5

schedulers:
  config:
    assignedTreads: 10
    cronExpression: "0 * * * * *"
    corePoolSize: 5
    maximumPoolSize: 20
    queueCapacity: 1000
    publish:
      threadNamePrefix: "publishing-"
      cronExpression: "0 * * * * *"
    moderation:
      threadNamePrefix: "moderation-"
      cronExpression: "0 * * * * *"
  correct-posts: "0 0 12 * * ?"
  post-cache:
    cleanup-cron: "0 0 0 * * ?" # Run at midnight every day

commenter-banner:
  cron: "0 0 12 * * ?"
  comments-count-for-ban: 5

app:
  kafka:
    topics:
      analytics:
        like: ${KAFKA_ANALYTICS_LIKE_TOPIC:analytics_like_topic}
  thread-pool:
    core-size: 5
    max-size: 10
    queue-capacity: 100
  speller:
    url: ${SPELLCHECKER_URL:"https://speller.yandex.net/services/spellservice.json"}
    max-request-uri-length: 10000
    max-content-length: 4096
    base-url-length: 70
    separator-length: 6
    async:
      core-pool-size: 10
      max-pool-size: 50
      queue-capacity: 100
      thread-name-prefix: "Async-"
    retry:
      maxAttempts: 5
      backoffDelay: 1000
  newsfeed:
    cache:
      post-ttl: 24h
      user-ttl: 24h
